### ISSUE TITLE
Not able to read model JSON 

### ISSUE THREAD

**Issue by rahuljim** [Azure/spark-cdm-connector#36] opened 2020-06-22 07:21 UTC
![image](https://user-images.githubusercontent.com/58183111/85259514-d4fa1d00-b486-11ea-8e1e-f81afacad350.png)
spark.read.format("com.microsoft.cdm") .option("storage", ".dfs.core.windows.net") .option("container", "cdmtest") .option("manifest", "/model.json") .option("entity", "contact") .option("appId",-ba011e") .option("appKey", "7Q3") .option("tenantId", "3503d") .load()

/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
170 return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
171 else:
--> 172 return self._df(self._jreader.load())
173
174 @SInCE(1.4)

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in call(self, *args)
1255 answer = self.gateway_client.send_command(command)
1256 return_value = get_return_value(
-> 1257 answer, self.gateway_client, self.target_id, self.name)
1258
1259 for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
61 def deco(*a, **kw):
62 try:
---> 63 return f(*a, **kw)
64 except py4j.protocol.Py4JJavaError as e:
65 s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
326 raise Py4JJavaError(
327 "An error occurred while calling {0}{1}{2}.\n".
--> 328 format(target_id, ".", name), value)
329 else:
330 raise Py4JError(

Py4JJavaError: An error occurred while calling o498.load.
: java.lang.RuntimeException: Manifest doesn't exist: model.json
at com.microsoft.cdm.utils.CDMModelCommon.getEntityDec(CDMModelCommon.scala:82)
at com.microsoft.cdm.read.CDMDataSourceReader.(CDMDataSourceReader.scala:28)
at com.microsoft.cdm.DefaultSource.createReader(DefaultSource.scala:99)
at com.microsoft.cdm.DefaultSource.createReader(DefaultSource.scala:19)
at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$SourceHelpers.createReader(DataSourceV2Relation.scala:155)
at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$.create(DataSourceV2Relation.scala:172)
at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:290)
at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:203)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
at py4j.Gateway.invoke(Gateway.java:295)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:7

**Comment by sricheta92** [comment] 2020-06-22 07:42
Closing this ticket as #33 is a duplicate of this.

**Closed by sricheta92** 2020-06-22 07:42 UTC
